# Generated by Django 3.2.9 on 2021-11-06 16:05

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('default_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('default_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('default_city', models.CharField(blank=True, max_length=45, null=True)),
                ('default_zipcode', models.CharField(blank=True, max_length=25, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('default_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('seller_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
