# Generated by Django 3.2.9 on 2021-12-18 15:02

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('default_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default_phone', models.CharField(blank=True, max_length=16, null=True)),
                ('default_address1', models.CharField(blank=True, max_length=80, null=True)),
                ('default_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('default_city', models.CharField(blank=True, max_length=50, null=True)),
                ('default_state', models.CharField(blank=True, max_length=50, null=True)),
                ('default_zipcode', models.CharField(blank=True, max_length=25, null=True)),
                ('default_country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.userprofile')),
                ('store_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('store_slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Vendor Profiles',
            },
            bases=('profiles.userprofile',),
        ),
    ]
