# Generated by Django 3.2.9 on 2021-12-13 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20211213_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vendor_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vendorprofile', to='profiles.vendorprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='store_owner',
            field=models.CharField(max_length=254),
        ),
    ]
