# Generated by Django 3.2.9 on 2021-12-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_phone',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
