# Generated by Django 3.2.9 on 2021-12-11 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_default_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='seller_balance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='store_name',
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('store_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.userprofile')),
            ],
        ),
    ]
