# Generated by Django 3.2.9 on 2021-12-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20211213_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='store_slug',
            field=models.SlugField(default='mikes-gpu-store', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='store_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
