# Generated by Django 3.2.9 on 2021-12-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20211213_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='vendor',
            field=models.BooleanField(default=False),
        ),
    ]
