# Generated by Django 3.2.9 on 2021-12-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='vendor_balance_paid',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='vendor_balance_unpaid',
        ),
    ]
