# Generated by Django 3.2.9 on 2021-12-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20211214_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='vendor',
            new_name='vendor_status',
        ),
    ]
