# Generated by Django 3.2.9 on 2021-12-18 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('category_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(editable=False, max_length=20)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('brand', models.CharField(choices=[('AMD', 'AMD'), ('ASUS', 'ASUS'), ('EVGA', 'EVGA'), ('GIGABYTE', 'GIGABYTE'), ('MSI', 'MSI'), ('Nvidia', 'Nvidia'), ('SAPPHIRE', 'SAPPHIRE'), ('XFX', 'XFX')], max_length=120)),
                ('boost_clock', models.CharField(max_length=15)),
                ('memory_clock', models.CharField(max_length=15)),
                ('memory_size', models.CharField(max_length=20)),
                ('memory_type', models.CharField(max_length=10)),
                ('interface_type', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, default='products/default.jpg', null=True, upload_to=product.models.image_file_rename)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='products/thumbnails/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcategory', to='product.category')),
            ],
            options={
                'verbose_name_plural': 'Products',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body_content', models.TextField(max_length=600)),
                ('rating', models.IntegerField(choices=[(5, 'Five'), (4, 'Four'), (3, 'Three'), (2, 'Two'), (1, 'One')], default=5)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('product_reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product')),
            ],
            options={
                'verbose_name_plural': 'Reviews',
                'ordering': ['-added_on'],
            },
        ),
        migrations.CreateModel(
            name='ProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name_plural': 'Product Names',
                'ordering': ['-category', '-product_name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productname', to='product.productname'),
        ),
    ]
