# Generated by Django 3.2.9 on 2021-12-13 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_seller'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productname',
            options={'ordering': ['-category', '-product_name'], 'verbose_name_plural': 'Product Names'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcategory', to='product.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productname', to='product.productname'),
        ),
    ]
