# Generated by Django 3.2.9 on 2021-12-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body_content',
            field=models.TextField(max_length=600),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')]),
        ),
    ]
