# Generated by Django 3.2.9 on 2021-12-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20211214_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(5, 'Five'), (4, 'Four'), (3, 'Three'), (2, 'Two'), (1, 'One')]),
        ),
    ]
