# Generated by Django 3.2.9 on 2021-12-13 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20211213_1525'),
        ('checkout', '0004_auto_20211213_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vendor',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='profiles.vendorprofile'),
            preserve_default=False,
        ),
    ]
