# Generated by Django 3.2.9 on 2021-12-06 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_alter_order_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='order_num',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='checkout.order'),
            preserve_default=False,
        ),
    ]
