# Generated by Django 3.2.9 on 2021-12-08 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_rename_related_order_orderitem_order_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_num',
            new_name='related_order',
        ),
    ]
