# Generated by Django 3.2.9 on 2021-12-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_order_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'Billing Addresses'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.AddField(
            model_name='orderitem',
            name='related_order',
            field=models.CharField(default=12343456, editable=False, max_length=32),
            preserve_default=False,
        ),
    ]
