# Generated by Django 3.2.9 on 2021-12-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_rename_order_num_orderitem_related_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
    ]
