# Generated by Django 3.2.9 on 2021-12-10 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_auto_20211209_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
    ]
