# Generated by Django 3.2.9 on 2021-12-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_order_stripe_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingdetails',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='shippingdetails',
            name='last_name',
        ),
        migrations.AddField(
            model_name='shippingdetails',
            name='full_name',
            field=models.CharField(default='testTest', max_length=175),
            preserve_default=False,
        ),
    ]
